package MyPage::Web::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MyPage::Web::Schema',
    
    
);

=head1 NAME

MyPage::Web::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MyPage::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MyPage::Web::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

vagrant

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
